"""add unique constraint to vehicle_id v2

Revision ID: 1a82e645f3ca
Revises: bf44b734b565
Create Date: 2025-12-07 16:49:36.724001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a82e645f3ca'
down_revision: Union[str, None] = 'bf44b734b565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_id', table_name='telemetry')
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.drop_index('ix_telemetry_vehicle_id', table_name='telemetry')
    op.create_index(op.f('ix_telemetry_vehicle_id'), 'telemetry', ['vehicle_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_vehicle_id'), table_name='telemetry')
    op.create_index('ix_telemetry_vehicle_id', 'telemetry', ['vehicle_id'], unique=False)
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.create_index('ix_telemetry_id', 'telemetry', ['id'], unique=False)
    # ### end Alembic commands ###
