"""initial

Revision ID: 46a8e1495442
Revises: 
Create Date: 2025-12-07 17:28:14.539012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a8e1495442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Integer(), nullable=False),
    sa.Column('dtc_code', sa.String(), nullable=True),
    sa.Column('tps_percent', sa.Float(), nullable=True),
    sa.Column('batt_volt', sa.Float(), nullable=True),
    sa.Column('fuel_trim_short', sa.Float(), nullable=True),
    sa.Column('o2_volt', sa.Float(), nullable=True),
    sa.Column('map_kpa', sa.Float(), nullable=True),
    sa.Column('vehicle_model', sa.String(), nullable=True),
    sa.Column('status', sa.JSON(), nullable=False),
    sa.Column('ai_advice', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_vehicle_id'), 'telemetry', ['vehicle_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_vehicle_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###
