# Initial setup


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8217aecbf379'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.alter_column('ai_advice',
                              existing_type=sa.VARCHAR(),
                              type_=postgresql.JSON(astext=True), # Menggunakan postgresql.JSON dengan astext=True disarankan
                              existing_nullable=True,
                              # 👇 PERBAIKAN: Tambahkan instruksi USING untuk konversi data
                              # Konversi dari VARCHAR/TEXT ke JSON secara eksplisit
                              postgresql_using='ai_advice::text::json' 
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        # Peringatan: Konversi JSON ke VARCHAR/TEXT dapat menyebabkan pemotongan data jika data JSON kompleks.
        batch_op.alter_column('ai_advice',
                              existing_type=postgresql.JSON(astext=True),
                              type_=sa.VARCHAR(),
                              existing_nullable=True,
                              # Konversi kembali (Misalnya, mengubah JSON menjadi string teks)
                              postgresql_using='ai_advice::text' 
        )

    # ### end Alembic commands ###