"""add unique constraint to vehicle_id

Revision ID: bf44b734b565
Revises: 8217aecbf379
Create Date: 2025-12-07 16:47:34.660967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf44b734b565'
down_revision: Union[str, None] = '8217aecbf379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_id', table_name='telemetry')
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.create_index('ix_telemetry_id', 'telemetry', ['id'], unique=False)
    # ### end Alembic commands ###
